### ISSUE TITLE
"Hold still" countdown before warping.

### ISSUE THREAD

**Issue by Falkirks** [Falkirks/SimpleWarp#12]
> Falk. can you add this cool and useful feature to simpleWarp?
> 
> it's when a player do the warp {name} command before teleporting he needs to wait 5 seconds WITHOUT moving if they move the Action get cancelled.
> 
> that's for to do not go out of combat mode by warping.
> 
> Thanks

**Comment by Falkirks** [comment]
This may end up being implemented in a separate extension plugin.

**Comment by TahaTheHacker** [comment]
oh.
