### ISSUE TITLE
Normal players can warp others

### ISSUE THREAD

**Issue by AryToNeX** [Falkirks/SimpleWarp#13]
In my server normal players can warp others. I already denied simplewarp.command.warp.others permission by using PurePerms but... it still happens..

**Comment by Falkirks** [comment]
It is `simplewarp.command.warp.other`, sorry for the confusion.

**Comment by AryToNeX** [comment]
My fault creating the issue ticket. I have denied the correct permission ```simplewarp.command.warp,other```
