### ISSUE TITLE
Warp does not exist message?

### ISSUE THREAD

**Issue by Bidou0418** [Falkirks/SimpleWarp#14]
whats up whith this message?
I do list warps and they are all there but when I try to warp it says warp doesn't exist???
Using 2.1

**Comment by Falkirks** [comment]
That's weird, what `storage-mode` are you using?

**Comment by patrickt1220** [comment]
Im having the same problem, however there are no errors in console.

**Comment by Falkirks** [comment]
@patrickt1220 What storage mode are you using?
