### ISSUE TITLE
API help

### ISSUE THREAD

**Issue by AndreyNazarchuk** [Falkirks/SimpleWarp#15]
How would I use the api to run a command when someone steps into the warp?
Thanks

**Comment by Falkirks** [comment]
You would want to register an event listener for `falkirks\simplewarp\event\PlayerWarpEvent` and then when that is run you can execute the command.

**Comment by AndreyNazarchuk** [comment]
Thanks
What does the warp event accept?
Like can I do $event->getPlayer() or $event->getWarp()?

**Comment by AndreyNazarchuk** [comment]
Nevermind I found it. Thanks for making this awesome plugin.
