### ISSUE TITLE
New Memory Support 

### ISSUE THREAD

**Issue by KairusDarkSeeker** [Falkirks/SimpleWarp#17]
Pls add a memory support that saves the warps.yml file and overwrites pls add it I don't want to add another warp again when I close and open the server it doesn't load warps

**Comment by Falkirks** [comment]
Maybe you are looking for `NO_MEMORY_STORE` or `FLUSH_ON_CHANGE` storage modes?These can be configured in the `config.yml`.

If you need something else feel free to open the issue and provide more information.
