### ISSUE TITLE
Filesize up from 23.5kb to 628kb?

### ISSUE THREAD

**Issue by frankblob** [Falkirks/SimpleWarp#18]
The bump from 2.1.0 to 2.1.1 made the phar increase from 23.5kb to 628kb in file size :)

**Comment by Falkirks** [comment]
I accidentally bundled the images in 2.1.1. They will be removed in the next version.

**Comment by Falkirks** [comment]
I update the release artifact on GitHub, but the one on the PocketMine forums will remain at 628kb.
