### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by XShockinFireX** [Falkirks/SimpleWarp#19]
Unhandled exception executing command 'warp Shop' in warp: Call to undefined method EssentialsPE\Loader::warpExists()
[14:28:43] [Server thread/CRITICAL]: Error: "Call to undefined method EssentialsPE\Loader::warpExists()" (EXCEPTION) in "/SimpleWarp_v2.1.1.phar/src/falkirks/simplewarp/command/essentials/EssentialsWarpCommand" at line 42

i get this error when i try to warp. i have EssentialsPE installed and enabled essentials support in the config.yml.

**Comment by Falkirks** [comment]
Disable `essentials-support`, it doesn't seem compatible with the version of Essentials you have installed. What version do you have?

**Comment by XShockinFireX** [comment]
version 2.0.0

**Comment by Falkirks** [comment]
@iksaku removed the API methods in version `2.0.0` so all `2.x.x` versions are not supported by SimpleWarp.

**Comment by iksaku** [comment]
We moved our APIs from `Loader` to `BaseAPI`, you can easily redirect your reference objects ;)

**Comment by Falkirks** [comment]
@iksaku Thanks for pointing that out. However, I will now need to check what EssentialsPE version is running in order to pick the correct class. It would have been much cleaner if you forwarded the method calls yourself.
