### ISSUE TITLE
World is not loaded

### ISSUE THREAD

**Issue by freshkitty** [Falkirks/SimpleWarp#20]
I seem to be getting a message every time I try to warp to a specific world or location in that world, it says that the World is not loaded, even if I'm in it. Anything I can do?

**Comment by Falkirks** [comment]
Your world name might be inconsistent with the folder name or the level data. Apparently sometimes issues arise like this.

**Comment by Bidou0418** [comment]
That is exactly the problem.
I resolved by correcting the server.properties (Level Name).
I had to change it to New World versus world.

**Comment by YanSoo123** [comment]
Same problem with me... but my world is called Survival and its not imported and it used to be world... So do I just change the level's name and it should work?

**Comment by Falkirks** [comment]
Try doing that

**Comment by YanSoo123** [comment]
I think the proble seems to be that this plugin is not compatible with genisys... are you guys running genisys?

**Comment by YanSoo123** [comment]
I think I found the issue... when you add a warp it says what level you added it on... If that level's name was changed... EVER... then the world will never work unless you use the original level name. OR... You could download many worlds and do /manyworlds fixname <world> then you can do /addwarp <warp> and create your warp

**Comment by Falkirks** [comment]
I am not sure how I could fix that. Would using the folder name be better? The world id? I thought those two values were much more mutable than the name.
