### ISSUE TITLE
Warp doesnt exist

### ISSUE THREAD

**Issue by Bidou0418** [Falkirks/SimpleWarp#21]
i do setwarp xxx, make a sign and test(WarpSigns), then i restart server and then, i get warp doesnt exist...
This also happens when using simplewarp without signs.

build; Genisys 380 latest

You previously claimed it was likely due to the server not restarting gracefully(Genisys) and data not being saved properly.
I had the same problem with essentialspe and their warp setup.
They managed to correct it.
However, i really like your WarpSigns plugin and was hoping you could adapt it to function either by using the essentialspe warps or modifying SimpleWarp to save the data properly even when using Genisys???

**Comment by Falkirks** [comment]
SimpleWarp saves in a different way than EssentialsPE by default. You should look at https://github.com/Falkirks/SimpleWarp/blob/master/resources/config.yml#L14-34. You might fix the issue by changing the `storage-mode` to `1` or `2`.
