### ISSUE TITLE
Synapse

### ISSUE THREAD

**Issue by DaMatrix** [Falkirks/SimpleWarp#28]
Would it be difficult to add synapse transfer support? It shouldn't take any more than soft depending on SynapseTransfer and calling SynapseClient->transfer based on name

**Comment by Falkirks** [comment]
Does synapse work?

**Comment by DaMatrix** [comment]
Yep. My server runs behind a Nemisys server, which is a java implementation of synapse.

**Comment by DaMatrix** [comment]
It works perfectly fine.

**Comment by Sandertv** [comment]
I'm just going to bump this issue. @Falkirks MCPE has added a TransferPacket, which you can easily use with $player->transfer(), if I'm correct, in the newer PocketMine versions. Might be a good idea to check that out.

**Comment by Falkirks** [comment]
SimpleWarp comes with FastTransfer support built in, so someone just needs to update FastTransfer or publish a new version.

**Comment by Falkirks** [comment]
Added in 98f59d6
