### ISSUE TITLE
WarpSign Reading warps.yml from EssentialsPE instead of Simplewarp

### ISSUE THREAD

**Issue by anti2canz** [Falkirks/SimpleWarp#31]
I have both EssentialsPE and Simplewarp installed as plugin, EssentialsPE will auto disable its warp function so im using simplewarp which is good.
However, Warpsign reads warp info from EssentialsPE insted of Simplewarps' warps.yml which cause the sign to say "warp doesnt exist". Is there anyway to fix this issue?

**Comment by Falkirks** [comment]
Huh. Does it work when EssentialsPE is not installed?

**Comment by Falkirks** [comment]
You can manually disable EssentialsPE support in the config file.

**Comment by anti2canz** [comment]
It works when EssentialsPE is removed, the essentials-support is already false by default in the config but doesnt work.

**Comment by Falkirks** [comment]
Will it work with warps in the essentials config? I don't understand how this is happening.

**Comment by Sandertv** [comment]
Oops, I forgot to disable warp signs if Warps are disabled, this is my fault, I'll fix it soon.

**Comment by Sandertv** [comment]
Sorry for the inconvenience, it's fixed.
(65e683eaf46221e7cc85e704604a8ff786eef4e6)
