### ISSUE TITLE
Warp Other

### ISSUE THREAD

**Issue by BlackZeroPM** [Falkirks/SimpleWarp#34]
I don't know why players can warp to other player (I tried to set simplewarp.command.other to false but still not work. Need help!

**Comment by Sandertv** [comment]
Have you got EssentialsPE installed?

**Comment by jrodr10** [comment]
same issue, yes essentials is installed. for now

**Comment by Falkirks** [comment]
Do you have EssentialsPE compatibility enabled in your config file?

**Comment by Falkirks** [comment]
@BlackZeroPM The permission node is `simplewarp.command.warp.other` just so ya know

**Comment by jrodr10** [comment]
Well not anymore lmao ive tested it out for months ended up just making my own plugin Lol

**Comment by Falkirks** [comment]
@jrodr10 Could you let me know though, so I can try to fix the issue 😛

**Comment by Sandertv** [comment]
@Falkirks I'm quite sure this has been an EssentialsPE issue which wrong permissions, not from SimpleWarp. After testing it everything seemed to be right.
