### ISSUE TITLE
Permission 

### ISSUE THREAD

**Issue by XDqrkneZ** [Falkirks/SimpleWarp#37]
how do you make players have permissions to warp to a   certain warp? like how essential is, the perms is essentials.warps.spawn and that allows  a player to warp spawn.. so how about SimpleWarp? What is the permissions?

**Comment by Falkirks** [comment]
`simplewarp.warp.spawn` for a warp called spawn.
`simplewarp.warp` for all warps.

If you run `/openwarp spawn` then SimpleWarp won't worry about permissions and just let anyone use the warp.

**Comment by XDqrkneZ** [comment]
ok tyyyyyy

**Comment by TaiXeko** [comment]
you are no permission

**Comment by SourSmirnoff** [comment]
problem is there is a bypass that is killing my server^
using /warp [warpName] [playerName] they can teleport to any warp
