### ISSUE TITLE
Permission issue

### ISSUE THREAD

**Issue by shoghicp** [Falkirks/SimpleWarp#4]
Some users are reporting incompatibility issues with SimpleAuth, related to permissions.

Specifically when the user has the plugin installed, it causes SimpleAuth commands to not to be able to be executed.

Maybe this is caused in combination with other plugins, but I'm opening this to keep track of its status and other findings.

**Comment by Falkirks** [comment]
I have been getting reports about this for a while. Hopefully we can get to the bottom of this. I believe other plugins caused this, but I haven't seen this reported in a while.

**Comment by Falkirks** [comment]
I am rewriting everything in the next version, maybe this will help.

**Comment by 3lawy** [comment]
Hi falk i just started my own server by pocket mine but it seems i am not the owner of the server because when i do /openwarp the server send :you don t have the premission of this command please help.

**Comment by Falkirks** [comment]
Are you OP ? Type `op [name` in your console.

**Comment by Falkirks** [comment]
I haven't gotten any reports of this after rewriting the plugin. If anyone finds this is still an issue please update here.
