### ISSUE TITLE
Inconvenience to get warp presence

### ISSUE THREAD

**Issue by SOF3** [Falkirks/SimpleWarp#40]
SimpleWarpAPI::getWarp() is hinted to return `Warp` while it may return null from WarpManager. API users have to use `SimpleWarpAPI::getWarpManager()[$name]` to workaround this, which renders getWarp() useless.

Recommended fix is to remove the `: Warp` typehint on `SimpleWarpAPI::getWarp()`.

**Comment by Falkirks** [comment]
Oh. Good recommendation. Can't drop PHP 7.0 support with nullable return types.
