### ISSUE TITLE
Warp individual permissions

### ISSUE THREAD

**Issue by kenygamer** [Falkirks/SimpleWarp#43]
Example:
 `/warp spawn`
Players must have the `simplewarp.warp.spawn` permission in order to use the warp.

**Comment by Falkirks** [comment]
Is there an issue?

**Comment by kenygamer** [comment]
@Falkirks Answering your reply, is the feature already implemented?

**Comment by Falkirks** [comment]
Yes

**Comment by kenygamer** [comment]
@Falkirks I haven't noticed. Thank you anyway.
