### ISSUE TITLE
spoon

### ISSUE THREAD

**Issue by BlackZeroPM** [Falkirks/SimpleWarp#48]
I type yes but it still not working
![untitled](https://user-images.githubusercontent.com/26817045/34552386-a6d30124-f153-11e7-8037-a6cdc685fc9c.png)

**Comment by Falkirks** [comment]
Did you save the file and restart your server?

**Comment by BlackZeroPM** [comment]
yes. I did

**Comment by Falkirks** [comment]
What text editor did you use to change it? Did you make changes to anything else in the file?

**Comment by BlackZeroPM** [comment]
I tried Microsoft Word.
Just type "yes"

**Comment by Falkirks** [comment]
Microsoft word would not be your best bet because it will make other changes to the file. Try using Notepad or something like that.
