### ISSUE TITLE
Only ops can warp

### ISSUE THREAD

**Issue by FaZeFantasy** [Falkirks/SimpleWarp#5]
When people with permissions to warp it doesnt even say anything doesnt teleport them or say "you have been warped" not even the default rank does

**Comment by Falkirks** [comment]
I think this is an issue on your end. If you don't run `/openwarp`, the warp will use a permission node. The permission nodes are OP only by default.

**Comment by thetechnologydude** [comment]
When I do /openwarp then the warp name eg 
/openwarp hub. It says the warp does not exist
