### ISSUE TITLE
Can you help with this error?

### ISSUE THREAD

**Issue by randoman911** [Falkirks/SimpleWarp#51]
30.01 21:13:58 [Server] Server thread/CRITICAL TypeError: "Return value of falkirks\simplewarp\lang\TranslationManager::execute() must be of the type string, null returned" (EXCEPTION) in "SimpleWarp_v3.3.5.phar/src/falkirks/simplewarp/lang/TranslationManager" at line 34
30.01 21:13:58 [Server] Server thread/DEBUG #0 SimpleWarp_v3.3.5.phar/src/falkirks/simplewarp/api/SimpleWarpAPI(61): falkirks\simplewarp\lang\TranslationManager->execute(string no-permission-warp)

**Comment by Falkirks** [comment]
I will get a release posted shortly.
