### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by thefuncraftmcpe** [Falkirks/SimpleWarp#53]
Plugin cannot work when I do /warp. Please fix it.

**Comment by Falkirks** [comment]
What error do you get? What server version are you using?

**Comment by thefuncraftmcpe** [comment]
'An Unknown error occurred while attempting to perform this command'. I am using the latest 3.0.0-ALPHA11

**Comment by Falkirks** [comment]
Is that the only message that appears? Is there anything above it?

**Comment by Falkirks** [comment]
Can you run the command `warpreport` in your console and it will prompt you to create a new issue?
