### ISSUE TITLE
nonops can warp players

### ISSUE THREAD

**Issue by artulloss** [Falkirks/SimpleWarp#58]
Players can do /warp warpname player name without having any perms

```
SERVER VERSION: PocketMine-MP 1.7dev-829
API: 3 v 11
MCPE VERSION: 1.2.10
SOFTWARE: PMMP
SimpleWarp Version: LATEST
PLUGINS: NO CONFLICTS WORKS WITHOUT PLUGINS
storage-mode: JSON
essentials-support: NOT USING ESSENTIALS
```

```
COPY your warps.yml here
```

**Comment by artulloss** [comment]
nevermined. tested again and it works, however its still a massive problem on my server at the moment

**Comment by Falkirks** [comment]
@artulloss So does it work?

**Comment by artulloss** [comment]
I can't tell what issue is, for some reason guests can warp people anywhere which is pretty bad because we have grabbag which lets anyone do @a and move everyone to a warp. My guest perms are setup as follows:

Guest:
  alias: gst
  isDefault: true
  inheritance: []
  permissions:
  - -pocketmine.command.me
  - gb.cmd.rpt
  - pchat.colored.format
  - pchat.colored.nametag
  - pocketmine.command.list
  - pperms.command.ppinf
  - simplewarp.command.warp
  - worldtp.load
  worlds: []

**Comment by Falkirks** [comment]
Can you post your warps.yml file?

**Comment by artulloss** [comment]
ok will do,

---
MiniArena:
  x: -29.731200
  "y": 14.000000
  z: 320.490900
  level: PotPvP
  public: true
  metadata: []
InvisArena:
  x: 25.463700
  "y": 236.092000
  z: 367.256000
  level: PotPvP
  public: true
  metadata: []
DiamondPvP:
  x: -917.000000
  "y": 17.500000
  z: 12.000000
  level: Diamond
  public: true
  metadata: []
KitPvP:
  x: -1.581000
  "y": 7.000000
  z: 13.866500
  level: KitPvP
  public: true
  metadata: []
HackCage:
  x: -562.633600
  "y": 5.000000
  z: -532.444800
  level: Lobby
  public: false
  metadata: []
ComboPvPZone:
  x: 63.227000
  "y": 2.408500
  z: 64.920500
  level: ComboPvP
  public: true
  metadata: []
ComboPvP:
  x: 62.925800
  "y": 76.000000
  z: 63.028800
  level: ComboPvP
  public: true
  metadata: []
§l§fInfo§1/§4RULES:
  x: -559.700000
  "y": 5.000000
  z: -83.709300
  level: Lobby
  public: false
  metadata: []
Hub:
  x: -571.473000
  "y": 7.000000
  z: -95.541200
  level: Lobby
  public: false
  metadata: []
Rules:
  x: -559.844500
  "y": 5.000000
  z: -83.700000
  level: Lobby
  public: false
  metadata: []
stats:
  x: -558.562000
  "y": 4.000000
  z: -83.524200
  level: Lobby
  public: true
  metadata: []
RedRover:
  x: -1.269400
  "y": 52.000000
  z: -1.563600
  level: RedRover
  public: true
  metadata: []
Idk:
  x: -1034.300000
  "y": 8.000000
  z: -327.532700
  level: Lobby
  public: false
  metadata: []
build:
  x: -1060.083700
  "y": 2.000000
  z: -455.731600
  level: Lobby
  public: false
  metadata: []
Soup:
  x: 62.887700
  "y": 76.000000
  z: 62.881500
  level: SoupPvP
  public: true
  metadata: []
Diamond:
  x: 59.587900
  "y": 74.000000
  z: 59.962600
  level: Diamond
  public: true
  metadata: []
PotPvP:
  x: 64.845700
  "y": 138.000000
  z: 64.368600
  level: PotPvP
  public: true
  metadata: []
...

**Comment by artulloss** [comment]
And yea, I was wondering why that was a child perm of simplewarp.command.warp

**Comment by Falkirks** [comment]
@artulloss Yup. It's an old issue that nobody has brought up. The config has been that way for years.

**Comment by artulloss** [comment]
Glad its fixed 😄
