### ISSUE TITLE
Warps outside of loaded area

### ISSUE THREAD

**Issue by MinecraftHomeschool** [Falkirks/SimpleWarp#6]
23.06 22:04:44 [Server] Server thread/EMERGENCY Please upload the "/CrashDump_Tue_Jun_23-22.04.44-CDT_2015.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
23.06 22:04:44 [Server] Server thread/EMERGENCY An unrecoverable error has occurred and the server has crashed. Creating a crash dump
23.06 22:04:44 [Server] INFO Fatal error: Call to a member function saveAll() on null in phar:///plugins/SimpleWarp_v2.phar/src/falkirks/simplewarp/SimpleWarp.php on line 41
23.06 22:04:44 [Server] Server thread/INFO Disabling SimpleWarp v2
23.06 22:04:44 [Server] Server thread/NOTICE ArrayOutOfBoundsException: "Undefined index: address" (E_NOTICE) in "/SimpleWarp_v2.phar/src/falkirks/simplewarp/WarpManager" at line 173
23.06 22:04:44 [Server] Server thread/CRITICAL A warp with the name week2a is attached to a level which isn't loaded. It will be removed automatically when your server stops.
23.06 22:04:44 [Server] Server thread/INFO Enabling SimpleWarp v2
23.06 22:04:44 [Server] Server thread/INFO Loading...

**Comment by Falkirks** [comment]
Try with the v2.0.1

**Comment by MinecraftHomeschool** [comment]
28.06 13:29:22 [Server] Server thread/EMERGENCY Please upload the "/CrashDump_Sun_Jun_28-13.29.22-CDT_2015.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
28.06 13:29:22 [Server] Server thread/EMERGENCY An unrecoverable error has occurred and the server has crashed. Creating a crash dump
28.06 13:29:22 [Server] INFO Fatal error: Call to a member function getName() on null in phar:///plugins/SimpleWarp_v2.0.1.phar/src/falkirks/simplewarp/Destination.php on line 102

**Comment by Falkirks** [comment]
Your trying to view a warp to a level which isn't loaded. This is a new bug see #7
