### ISSUE TITLE
EssentialsPE compatibility

### ISSUE THREAD

**Issue by Falkirks** [Falkirks/SimpleWarp#9]
EssentialsPE wants to register `/warp` and `/delwarp`. This means there will be a very inconsistent experience for the end user. 

One way to solve this would be to hack EssentialsPE out of the command registration table and force into a fallback command. This done, SimpleWarp would register special command classes which would check both SimpleWarp and EssentialsPE for warps.

**Comment by legoboy0215** [comment]
Nice idea!
